named_conf: ./pdns_zones
zones_dir: ./output

ruby_zones: ./zones/
templates: ./templates/

# Command to run after push
execute: '/bin/echo happy'

# SOA Record
# Recommendations: http://www.ripe.net/ripe/docs/ripe-203
soa:
  primary: "ns1.example.com."
  email: "webmaster@example.com"
  ttl: "1H"
  refresh: "1D"
  retry: "3H"
  expire: "1W"
  minimumTTL: "2D"
